server {
    listen 80;
    server_name 48daklao.local;
    root /var/www;
    index index.html;
}

server {
    listen 80;
    server_name app.48daklao.local;
    root /var/www;
    index upload.php;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
    }
}

server {
    listen 80;
    server_name secret-dev.48daklao.local;
    root /var/www;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
    }
}